name: flame_forge2d_tiled
description: A package that combines Tiled Map Editor + Flame Game Engine with Physics
version: 0.2.0
homepage: https://github.com/aeb-dev/flame_forge2d_tiled
repository: https://github.com/aeb-dev/flame_forge2d_tiled
issue_tracker: https://github.com/aeb-dev/flame_forge2d_tiled/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.14.0
  flame_forge2d: ^0.16.0+4
  flutter:
    sdk: flutter
  tmx_parser: ^0.3.1

dev_dependencies:
  aeb_lint: ^1.1.0
  flutter_test:
    sdk: flutter
  test: ^1.21.4
