name: flame_forge2d_tiled
description: A package that combines [Tiled Map Editor](https://www.mapeditor.org) + [Flame Game Engine with Physics](https://github.com/flame-engine/flame)
version: 0.1.0
homepage: https://github.com/aeb-dev/flame_forge2d_tiled
repository: https://github.com/aeb-dev/flame_forge2d_tiled
issue_tracker: https://github.com/aeb-dev/flame_forge2d_tiled/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flame: ^1.0.0
  flame_forge2d: ^0.8.3
  forge2d: ^0.8.1
  tmx_parser: ^0.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
