name: flame_forge2d_tiled
description: A package that combines Tiled Map Editor + Flame Game Engine with Physics
version: 0.1.0
homepage: https://github.com/aeb-dev/flame_forge2d_tiled
repository: https://github.com/aeb-dev/flame_forge2d_tiled
issue_tracker: https://github.com/aeb-dev/flame_forge2d_tiled/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.2.1
  flame_forge2d: ^0.12.1
  tmx_parser:
    path: ../tmx_parser
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
