name: flame_forge2d_tiled
description: Tiled support for the Flame game engine.
version: 0.1.0
homepage: https://github.com/aeb-dev/flame_forge2d_tiled

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flame: ^1.0.0
  flame_forge2d: ^0.8.3
  tmx_parser: ^0.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
